feat: added `require-resource-quota` for multitenancy-benchmark category
nirmata/kyverno-policies pull request #117
Opened 2024-02-21 20:26 UTC by fykaa

## Policy Description
require-resource-quota: Namespace resource quotas should be used to allocate, track and limit the number of objects, of a particular type, that can be created within a namespace. In cases such as multi-tenancy where new Namespaces must be fully provisioned before they can be used, it may not be easy to declare and understand if/when the Namespace is ready. Having a policy which defines all the resources which are required for each Namespace can assist in determining compliance. This policy, expected to be run in background mode only, performs a Namespace check to ensure that all Namespaces have a ResourceQuota. Additional rules may be written to extend the check according to needs.

## Policy Category
Multitenancy Benchmark

2024-02-22 11:30 UTC, nsathyaseelan requested changes

2024-02-22 11:30 UTC, nsathyaseelan commented on multitenancy-benchmarks/require-resource-quota/.chainsaw-test/chainsaw-test.yaml
> +    - apply:
@fykaa  If this is expected to produce an error or fail, then the policy's validationFailure action should be set to **Enforce** mode. Could you please update the validationFailureAction comment by changing the value to Enforce mode: `validationFailureAction: Audit/validationFailureAction: Enforce`

2024-02-23 17:03 UTC, nsathyaseelan approved these changes

2024-02-25 20:11 UTC, anusha94 commented
@fykaa Would be nice to have a `README.md` for all multitenancy policies, like we have for kyverno-json policies. I'm merging this now, the README can be in a follow-up PR.

2024-02-25 20:11 UTC, anusha94 approved these changes

2024-02-25 20:11 UTC, merged