added synchronize to true in add-network-policy.yaml and bumped chart…
nirmata/kyverno-policies pull request #132
Opened 2024-05-16 08:44 UTC by anuddeeph1

… version

2024-05-16 08:51 UTC, pns-nirmata approved these changes

2024-06-17 07:07 UTC, anusha94 requested changes

2024-06-17 07:07 UTC, anusha94 commented on charts/multitenancy/pols/add-network-policy.yaml
> +      synchronize: true
You need to update it here as well - https://github.com/nirmata/kyverno-policies/blob/main/multitenancy/add-network-policy.yaml

2024-07-08 14:41 UTC, anusha94 commented
Please reopen PR if you still need it.

2024-07-08 14:41 UTC, closed without merging