Adding additional best practice policies
nirmata/kyverno-policies pull request #43
Opened 2023-02-27 14:26 UTC by nsagark

Adding additional best practice policies

2023-02-27 15:48 UTC, patelrit commented
Some comments:
- Please follow the same naming convention as other policies - for validate policies, please follow terms such as 'restrict', 'prevent', 'disallow' etc
- Please do not include any mutate or generate policies in the default policy sets as these policy sets will be included in default sets. We can create different policy sets for mutate and generate policies which can be available as optional.

2023-02-28 10:12 UTC, nsagark commented
I have renamed the validate policies and removed the mutate/generate policies. Please review

2023-03-16 15:58 UTC, anusha94 requested changes
There are other occurrences of `Other` and `Sample` in category annotation. Please remove those.

2023-03-16 15:58 UTC, anusha94 commented on best-practices/disallow_secrets_from_env_vars/disallow_secrets_from_env_vars.yaml
> +    policies.kyverno.io/category: Sample, EKS Best Practices
Do not use Sample as a category

2023-03-16 15:58 UTC, anusha94 commented on best-practices/prevent_orphan_pods/prevent_orphan_pods.yaml
> +    policies.kyverno.io/category: Other, EKS Best Practices
Do not use Other as a category

2023-05-22 21:03 UTC, closed without merging